apiVersion: v1
kind: Service
metadata:
  name: {{ include "opengym.fullname" . }}-api
  labels:
    {{- include "opengym.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "opengym.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
