apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opengym.fullname" . }}-config
  labels:
    {{- include "opengym.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.api.port | quote }}
  NGINX_PORT: {{ .Values.web.containerPort | quote }}
  BACKEND: {{ printf "%s-api" (include "opengym.fullname" .) | quote }}
  DATA_DIR: {{ .Values.config.dataDir | quote }}
  RP_ID: {{ default .Values.ingress.host .Values.config.rpId | quote }}
  ORIGIN: {{ default (printf "https://%s" .Values.ingress.host) .Values.config.origin | quote }}
