apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opengym.fullname" . }}-media
  labels:
    {{- include "opengym.labels" . | nindent 4 }}
  {{- with .Values.media.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.media.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.media.storage }}
  {{- with .Values.media.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
