apiVersion: v2
name: opengym
description: A Helm Chart for deploying openGym on Kubernetes

type: application

version: 0.1.0 # Fallback version, we're using semantic release for creating tagged versions on GitHub

appVersion: "1.2.9"
